routes/web.php
<?php

use App\Http\Controllers\Web\AuthController;
use App\Http\Controllers\Web\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    if (session('token')) return redirect(route('web.products.index'));
    return view('welcome');
})->name('/');


Route::get('/login', function () {
    if (session('token')) return redirect(route('web.products.index'));
    return view('login');
});

Route::post('register', [AuthController::class, 'register'])->name('register');
Route::post('login', [AuthController::class, 'login'])->name('login');

Route::group(['middleware' => 'check_session'], function () {
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');


    Route::resource('products', ProductController::class, ['as' => 'web']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        "name",
        "description",
        "price"
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends Controller
{

    public function __construct()
    {
        // $this->authorizeResource(Product::class, 'products');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return response()->json([
            "data" => Product::all()
        ], Response::HTTP_OK);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProductRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $product = Product::create($request->validated());
        return response()->json([
            'message' => 'Product added successfully!',
            'data' => $product
        ], Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $this->authorize('view', Product::class);

        if (!$product) {
            return response()->json([
                'message' => 'Not Found'
            ], Response::HTTP_NOT_FOUND);
        } else {
            return response()->json([
                'data' => $product
            ], Response::HTTP_OK);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateProductRequest  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        $product->update($request->validated());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

app/Http/Controllers/Web/ProductController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Models\Product;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Symfony\Component\HttpFoundation\Response as HttpFoundationResponse;

class ProductController extends Controller
{

    public function __construct()
    {
        $this->module_view_path = 'products.';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = array();
        if (Gate::allows('view-products')) {
            $req = Request::create('/api/products', 'GET');
            $req->headers->set('Accept', 'application/json');
            $res = app()->handle($req);

            if ($res->getStatusCode() === HttpFoundationResponse::HTTP_UNAUTHORIZED) {
                return redirect(route('login'))->with('danger', 'Please Login');
            }

            $data['products'] = $res->getStatusCode() === HttpFoundationResponse::HTTP_OK
                ? json_decode($res->getContent(), TRUE)['data']
                : [];
        }
        return view($this->module_view_path . 'index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->module_view_path . 'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        if (!Gate::allows('add-products'))
            abort(HttpFoundationResponse::HTTP_UNAUTHORIZED);

        $req = Request::create('/api/products', 'POST', $request->validated());
        $req->headers->set('Accept', 'application/json');
        app()->handle($req);
        return redirect(route('web.products.index'))
            ->with('success', 'Product Added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        abort_if(!$product, 'Product doesn\'t exsists!');
        return view($this->module_view_path . 'edit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateProductRequest  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        if (!Gate::allows('view-products'))
            abort(HttpFoundationResponse::HTTP_UNAUTHORIZED);


        $req = Request::create('/api/products/' . $product['id'], 'POST', $request->validated());
        $req->headers->set('Accept', 'application/json');

        $res = app()->handle($req);

        dd($res);

        return redirect(route('web.products.index'))
            ->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/products/create.blade.php
@extends('layout.app')
@section('content')

@can('add-products')
<section class="container">

    <div class="row">
        <h2 class="justify-content-center">Add Product</h2>
    </div>
    @include('layout.message')
    <form role="form" action="{{route('web.products.store')}}" method="post">
        @csrf

        <div class="mb-3">
            <label for="name" class="form-label">Product Name</label>
            <input type="text" value="{{old('name')}}" name="name" class="form-control" id="name" minlength="3" maxlength="100" required>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description" required minlength="5" maxlength="250">{{old('description')}}</textarea>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" value="{{old('price')}}" name="price" class="form-control" id="price" min="0" required>
        </div>

        <div class="mb-3">
            <a href="{{route('web.products.index')}}" class="btn btn-info btn-block float-right">Back</a>
            <button type="submit" class="btn btn-primary btn-block float-right" id="submit">Add Product</button>
        </div>
    </form>
</section>
@else
<div class="alert alert-danger">
    <p>This action is unauthorized</p>
</div>
@endcan
@endsection

resources/views/products/edit.blade.php
@extends('layout.app')
@section('content')

@can('update-products')
<section class="container">

    <div class="row">
        <h2 class="justify-content-center">Edit Product</h2>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <form role="form" action="{{route('web.products.update',$product['id'])}}" method="post">
        @csrf
        @method('PUT')

        <div class="mb-3">
            <label for="name" class="form-label">Product Name</label>
            <input type="text" name="name" value="{{$product['name']}}" class="form-control" id="name" minlength="3" maxlength="100" required>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" name="description" id="description" required minlength="5" maxlength="250">{{$product['description']}}</textarea>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" name="price" value="{{$product['price']}}" class="form-control" id="price" min="0" required>
        </div>

        <div class="mb-3">
            <a href="{{route('web.products.index')}}" class="btn btn-info btn-block float-right">Back</a>
            <button type="submit" class="btn btn-primary btn-block float-right" id="submit">Update Product</button>
        </div>
    </form>
</section>
@else
<div class="alert alert-danger">
    <p>This action is unauthorized</p>
</div>
@endcan
@endsection

resources/views/products/index.blade.php
@extends('layout.app')

@section('content')
@can('add-products')
<section class="container">
    <div class="row pull-left">
        <h3>Products</h3>
    </div>

    <div class="pull-right">
        <a class="btn btn-primary" href="{{route('web.products.create')}}"> Create New Product</a>
    </div>




    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif


    @if( isset($products) && count($products))
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                <th scope="col">Description</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            <tr>
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{$product['name']}}</td>
                <td>{{$product['description']}}</td>
                <td>{{$product['price']}}</td>
                <td>
                    <a href="{{route('web.products.edit',$product['id'])}}">Edit</a>&nbsp;&nbsp;
                    <a href="{{route('web.products.destroy',$product['id'])}}">Delete</a>
                </td>

            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p class="justify-content-center">No Products Added!</p>
    @endif
</section>
@else
<div class="alert alert-danger">
    <p>This action is unauthorized</p>
</div>
@endcan

@endsection